 Running on host airflow-worker-1
Traceback (most recent call last):
  File "/usr/local/airflow/dags/my_dag.py", line 42, in my_task
    raise ValueError("Invalid input data")
ValueError: Invalid input data
 Task failed with exception
