[2025-07-28, 11:00:20] ERROR - Task failed with exception
HTTPError: 403 Client Error: Forbidden for url: https://api.example.com/protected-resource
File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1026, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url
